[package]
name = "slipstream-ir"
version = "0.1.0"
edition = "2024"

[dependencies]
slipstream-derive = { path = "../slipstream-derive" }
slipstream-shared = { path = "../slipstream-shared" }

glam.workspace = true
egui.workspace = true

byteorder = "1.5.0"
tracing = "0.1.44"
bitfield-struct = "0.13.0"
parking_lot = { version = "0.12.5", features = ["arc_lock"] }
dashmap = "6.2.1"
strum = { version = "0.28.0", features = ["derive"] }
paste = "1.0.15"
bytemuck = "1.25.2"
nohash-hasher = "0.2.0"
rayon = "1.12.0"
parking_lot_core = "0.9.12"
downcast-rs = "2.0.2"
